# Generated by Django 4.2.6 on 2023-11-20 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BandaHoraria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('horario_inicio', models.DateTimeField()),
                ('horario_fin', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
                ('nota', models.IntegerField()),
                ('banda_horaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_alumno.bandahoraria')),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('dni', models.IntegerField(primary_key=True, serialize=False)),
                ('telefono', models.CharField(max_length=255)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_alumno.curso')),
            ],
        ),
    ]
