# Generated by Django 4.2.7 on 2023-11-20 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_alumno', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='dni',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
